
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { I18nextProvider } from "react-i18next";
import i18n from "./lib/i18n"; // Ensure this is the correct path to your i18n configuration file

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-archivo">
        {/* Wrap the application with the I18nextProvider */}
    
          {children}

      </body>
    </html>
  );
}
